packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
  prisma: true
  sharp: true
  unrs-resolver: true
