'use client';

import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import {
  AlertCircle, Bug, BookOpen, CheckSquare, ChevronRight, ExternalLink,
  Filter, Loader2, Plus, RefreshCw, Search, Sparkles, Star, X, Zap,
} from 'lucide-react';
import { useState } from 'react';
import { toast } from 'sonner';
import { api } from '@/lib/api';

function getErrorMessage(error: unknown) {
  return error instanceof Error ? error.message : 'Request failed';
}

// ── Types ─────────────────────────────────────────────────────────────────────

interface WorkItem {
  id: number;
  title: string;
  type: string;
  state: string;
  priority?: number;
  assignedTo?: string | null;
  description?: string | null;
  acceptanceCriteria?: string | null;
  tags?: string | null;
  areaPath?: string | null;
  iterationPath?: string | null;
  createdDate?: string;
  changedDate?: string;
  url?: string;
}

interface Agent {
  id: string;
  name: string;
  description?: string;
  skills: Array<{ skill: { name: string; type: string } }>;
}

interface WorkItemType {
  name: string;
  color?: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function typeIcon(type: string) {
  switch (type.toLowerCase()) {
    case 'bug': return <Bug size={14} className="text-red-500" />;
    case 'user story': return <BookOpen size={14} className="text-blue-500" />;
    case 'task': return <CheckSquare size={14} className="text-green-500" />;
    case 'feature': return <Star size={14} className="text-purple-500" />;
    case 'epic': return <Zap size={14} className="text-orange-500" />;
    default: return <AlertCircle size={14} className="text-gray-400" />;
  }
}

function stateColor(state: string) {
  const s = state.toLowerCase();
  if (s.includes('done') || s.includes('closed') || s.includes('resolved')) return 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400';
  if (s.includes('progress') || s.includes('active') || s.includes('doing')) return 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400';
  if (s.includes('review') || s.includes('testing')) return 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400';
  if (s.includes('removed') || s.includes('cancelled')) return 'bg-gray-100 text-gray-500 dark:bg-gray-800 dark:text-gray-500';
  return 'bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400';
}

function priorityLabel(p?: number) {
  switch (p) {
    case 1: return { label: 'Critical', color: 'text-red-500' };
    case 2: return { label: 'High', color: 'text-orange-500' };
    case 3: return { label: 'Medium', color: 'text-yellow-500' };
    case 4: return { label: 'Low', color: 'text-gray-400' };
    default: return null;
  }
}

// ── AI Generate Panel (work-item specific) ─────────────────────────────────────

function WorkItemAIPanel({
  projectId,
  agents,
  workItemType,
  onGenerated,
  onClose,
}: {
  projectId: string;
  agents: Agent[];
  workItemType: string;
  onGenerated: (data: Record<string, string | number>) => void;
  onClose: () => void;
}) {
  const [mode, setMode] = useState<'direct' | 'agent'>('direct');
  const [description, setDescription] = useState('');
  const [selectedAgentId, setSelectedAgentId] = useState('');
  const [loading, setLoading] = useState(false);

  async function generate() {
    if (!description.trim()) { toast.error('Please describe what you want to create'); return; }
    setLoading(true);
    try {
      if (mode === 'direct') {
        const res = await api.post<{ data: Record<string, string | number> }>('/api/ai/generate', {
          type: 'work-item',
          description,
          workItemType,
        });
        onGenerated(res.data);
        toast.success('Work item generated by AI ✨');
      } else {
        if (!selectedAgentId) { toast.error('Select an agent first'); setLoading(false); return; }
        const res = await api.post<{ data: Record<string, string | number> }>(
          `/api/projects/${projectId}/work-items/agent-generate`,
          { agentId: selectedAgentId, description, workItemType }
        );
        onGenerated(res.data);
        const agent = agents.find((a) => a.id === selectedAgentId);
        toast.success(`Generated via agent "${agent?.name ?? 'Agent'}" ✨`);
      }
    } catch (error) {
      toast.error(getErrorMessage(error));
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mb-6 rounded-xl border border-indigo-200 bg-gradient-to-br from-indigo-50 to-purple-50 p-5 dark:border-indigo-800 dark:from-indigo-900/20 dark:to-purple-900/20">
      <div className="mb-3 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <Sparkles size={16} className="text-indigo-500" />
          <span className="font-semibold text-indigo-700 dark:text-indigo-300">Generate with AI</span>
        </div>
        <button onClick={onClose} className="text-gray-400 hover:text-gray-600 dark:hover:text-gray-300">
          <X size={16} />
        </button>
      </div>

      {/* Mode toggle */}
      <div className="mb-3 flex gap-2">
        <button
          onClick={() => setMode('direct')}
          className={`rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${mode === 'direct' ? 'bg-indigo-600 text-white' : 'bg-white text-gray-600 hover:bg-indigo-50 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-indigo-900/30'}`}
        >
          Direct AI
        </button>
        {agents.length > 0 && (
          <button
            onClick={() => setMode('agent')}
            className={`flex items-center gap-1 rounded-lg px-3 py-1.5 text-xs font-medium transition-colors ${mode === 'agent' ? 'bg-indigo-600 text-white' : 'bg-white text-gray-600 hover:bg-indigo-50 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-indigo-900/30'}`}
          >
            <Zap size={11} /> Use Agent
          </button>
        )}
      </div>

      {/* Agent picker */}
      {mode === 'agent' && (
        <div className="mb-3">
          <select
            value={selectedAgentId}
            onChange={(e) => setSelectedAgentId(e.target.value)}
            className="w-full rounded-lg border border-indigo-200 bg-white px-3 py-2 text-sm text-gray-700 dark:border-indigo-700 dark:bg-gray-800 dark:text-gray-200"
          >
            <option value="">Select agent…</option>
            {agents.map((a) => (
              <option key={a.id} value={a.id}>
                {a.name} ({a.skills.length} skill{a.skills.length !== 1 ? 's' : ''})
              </option>
            ))}
          </select>
          {selectedAgentId && (
            <p className="mt-1 text-xs text-indigo-500 dark:text-indigo-400">
              Skills: {agents.find((a) => a.id === selectedAgentId)?.skills.map((s) => s.skill.name).join(', ') || 'none'}
            </p>
          )}
        </div>
      )}

      <textarea
        value={description}
        onChange={(e) => setDescription(e.target.value)}
        onKeyDown={(e) => { if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) generate(); }}
        rows={3}
        className="w-full rounded-lg border border-indigo-200 bg-white px-3 py-2.5 text-sm placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-300 dark:border-indigo-700 dark:bg-gray-800 dark:text-white dark:placeholder-gray-500 dark:focus:ring-indigo-600"
        placeholder={`Describe what you want to create as a ${workItemType}… (Ctrl+Enter to generate)`}
      />
      <button
        onClick={generate}
        disabled={loading || !description.trim()}
        className="mt-2 flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50"
      >
        {loading ? <Loader2 size={14} className="animate-spin" /> : <Sparkles size={14} />}
        {loading ? 'Generating…' : 'Generate'}
      </button>
    </div>
  );
}

// ── Work Item Detail Panel ─────────────────────────────────────────────────────

function WorkItemDetail({ item, onClose }: { item: WorkItem; onClose: () => void }) {
  const pri = priorityLabel(item.priority);
  return (
    <div className="flex flex-col h-full">
      <div className="flex items-start justify-between gap-2 mb-4">
        <div className="flex items-center gap-2 min-w-0">
          {typeIcon(item.type)}
          <span className="text-xs font-medium text-gray-500 dark:text-gray-400">{item.type} #{item.id}</span>
        </div>
        <button onClick={onClose} className="shrink-0 text-gray-400 hover:text-gray-600">
          <X size={16} />
        </button>
      </div>

      <h2 className="mb-3 text-base font-semibold text-gray-900 dark:text-white">{item.title}</h2>

      <div className="flex flex-wrap gap-2 mb-4">
        <span className={`rounded-full px-2.5 py-0.5 text-xs font-medium ${stateColor(item.state)}`}>{item.state}</span>
        {pri && <span className={`text-xs font-medium ${pri.color}`}>{pri.label}</span>}
        {item.assignedTo && <span className="text-xs text-gray-500 dark:text-gray-400">→ {item.assignedTo}</span>}
        {item.url && (
          <a href={item.url} target="_blank" rel="noopener noreferrer"
            className="flex items-center gap-1 text-xs text-indigo-500 hover:text-indigo-700">
            <ExternalLink size={11} /> Open in ADO
          </a>
        )}
      </div>

      {item.description && (
        <div className="mb-4">
          <h4 className="mb-1 text-xs font-semibold uppercase tracking-wide text-gray-400 dark:text-gray-600">Description</h4>
          <div
            className="prose prose-sm max-w-none text-gray-700 dark:prose-invert dark:text-gray-300"
            dangerouslySetInnerHTML={{ __html: item.description }}
          />
        </div>
      )}

      {item.acceptanceCriteria && (
        <div className="mb-4">
          <h4 className="mb-1 text-xs font-semibold uppercase tracking-wide text-gray-400 dark:text-gray-600">Acceptance Criteria</h4>
          <div
            className="prose prose-sm max-w-none text-gray-700 dark:prose-invert dark:text-gray-300"
            dangerouslySetInnerHTML={{ __html: item.acceptanceCriteria }}
          />
        </div>
      )}

      {item.tags && (
        <div className="flex flex-wrap gap-1">
          {item.tags.split(';').filter(Boolean).map((tag) => (
            <span key={tag} className="rounded bg-gray-100 px-1.5 py-0.5 text-xs text-gray-500 dark:bg-gray-800 dark:text-gray-400">
              {tag.trim()}
            </span>
          ))}
        </div>
      )}
    </div>
  );
}

// ── Create / Edit Form ─────────────────────────────────────────────────────────

function WorkItemForm({
  projectId,
  agents,
  workItemTypes,
  onSuccess,
  onClose,
}: {
  projectId: string;
  agents: Agent[];
  workItemTypes: WorkItemType[];
  onSuccess: () => void;
  onClose: () => void;
}) {
  const [showAI, setShowAI] = useState(false);
  const [form, setForm] = useState({
    type: workItemTypes[0]?.name ?? 'User Story',
    title: '',
    description: '',
    acceptanceCriteria: '',
    priority: 2,
    tags: '',
  });

  const createMutation = useMutation({
    mutationFn: () => api.post(`/api/projects/${projectId}/work-items`, form),
    onSuccess: () => {
      toast.success('Work item created in Azure DevOps ✔');
      onSuccess();
    },
    onError: (error) => toast.error(getErrorMessage(error)),
  });

  function applyAI(data: Record<string, string | number>) {
    setForm((prev) => ({
      ...prev,
      title: String(data.title ?? prev.title),
      description: String(data.description ?? prev.description),
      acceptanceCriteria: String(data.acceptanceCriteria ?? prev.acceptanceCriteria),
      type: String(data.type ?? prev.type),
      priority: typeof data.priority === 'number' ? data.priority : prev.priority,
      tags: String(data.tags ?? prev.tags),
    }));
    setShowAI(false);
    toast.success('Form pre-filled by AI — review and adjust');
  }

  const labelClass = 'mb-1 block text-xs font-medium text-gray-600 dark:text-gray-400';
  const inputClass = 'w-full rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:focus:ring-indigo-600';

  return (
    <div>
      <div className="mb-4 flex items-center justify-between">
        <h3 className="font-semibold text-gray-900 dark:text-white">New Work Item</h3>
        <div className="flex items-center gap-3">
          {!showAI && (
            <button onClick={() => setShowAI(true)} className="flex items-center gap-1.5 text-xs text-indigo-500 hover:text-indigo-700">
              <Sparkles size={12} /> Generate with AI
            </button>
          )}
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600"><X size={16} /></button>
        </div>
      </div>

      {showAI && (
        <WorkItemAIPanel
          projectId={projectId}
          agents={agents}
          workItemType={form.type}
          onGenerated={applyAI}
          onClose={() => setShowAI(false)}
        />
      )}

      <div className="space-y-3">
        {/* Type + Priority row */}
        <div className="flex gap-3">
          <div className="flex-1">
            <label className={labelClass}>Type</label>
            <select
              value={form.type}
              onChange={(e) => setForm((p) => ({ ...p, type: e.target.value }))}
              className={inputClass}
            >
              {(workItemTypes.length > 0 ? workItemTypes : [
                { name: 'User Story' }, { name: 'Bug' }, { name: 'Task' }, { name: 'Feature' }, { name: 'Epic' }
              ]).map((t) => (
                <option key={t.name} value={t.name}>{t.name}</option>
              ))}
            </select>
          </div>
          <div className="w-36">
            <label className={labelClass}>Priority</label>
            <select
              value={form.priority}
              onChange={(e) => setForm((p) => ({ ...p, priority: Number(e.target.value) }))}
              className={inputClass}
            >
              <option value={1}>1 – Critical</option>
              <option value={2}>2 – High</option>
              <option value={3}>3 – Medium</option>
              <option value={4}>4 – Low</option>
            </select>
          </div>
        </div>

        {/* Title */}
        <div>
          <label className={labelClass}>Title *</label>
          <input
            value={form.title}
            onChange={(e) => setForm((p) => ({ ...p, title: e.target.value }))}
            className={inputClass}
            placeholder="Short, descriptive title"
          />
        </div>

        {/* Description */}
        <div>
          <label className={labelClass}>Description</label>
          <textarea
            value={form.description}
            onChange={(e) => setForm((p) => ({ ...p, description: e.target.value }))}
            rows={4}
            className={inputClass}
            placeholder="HTML or plain text description"
          />
        </div>

        {/* Acceptance Criteria (for User Stories / Features) */}
        {['user story', 'feature'].includes(form.type.toLowerCase()) && (
          <div>
            <label className={labelClass}>Acceptance Criteria</label>
            <textarea
              value={form.acceptanceCriteria}
              onChange={(e) => setForm((p) => ({ ...p, acceptanceCriteria: e.target.value }))}
              rows={4}
              className={inputClass}
              placeholder="Given / When / Then criteria (HTML or plain text)"
            />
          </div>
        )}

        {/* Tags */}
        <div>
          <label className={labelClass}>Tags</label>
          <input
            value={form.tags}
            onChange={(e) => setForm((p) => ({ ...p, tags: e.target.value }))}
            className={inputClass}
            placeholder="tag1; tag2; tag3"
          />
        </div>

        <div className="flex justify-end gap-2 pt-2">
          <button
            onClick={onClose}
            className="rounded-lg border border-gray-300 px-4 py-2 text-sm text-gray-600 hover:bg-gray-50 dark:border-gray-600 dark:text-gray-400 dark:hover:bg-gray-800"
          >
            Cancel
          </button>
          <button
            onClick={() => createMutation.mutate()}
            disabled={createMutation.isPending || !form.title.trim()}
            className="flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700 disabled:opacity-50"
          >
            {createMutation.isPending ? <Loader2 size={14} className="animate-spin" /> : <Plus size={14} />}
            Create Work Item
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Main Component ─────────────────────────────────────────────────────────────

export function WorkItemsView({ projectId }: { projectId: string }) {
  const qc = useQueryClient();
  const [typeFilter, setTypeFilter] = useState('');
  const [stateFilter, setStateFilter] = useState('');
  const [search, setSearch] = useState('');
  const [selectedItem, setSelectedItem] = useState<WorkItem | null>(null);
  const [showCreate, setShowCreate] = useState(false);

  const { data, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: ['work-items', projectId, typeFilter, stateFilter],
    queryFn: () => {
      const params = new URLSearchParams({ top: '100' });
      if (typeFilter) params.set('type', typeFilter);
      if (stateFilter) params.set('state', stateFilter);
      return api.get<{ data: WorkItem[]; meta: { total: number } }>(
        `/api/projects/${projectId}/work-items?${params}`
      );
    },
  });

  const { data: typesData } = useQuery({
    queryKey: ['work-item-types', projectId],
    queryFn: () => api.get<{ data: WorkItemType[] }>(`/api/projects/${projectId}/work-item-types`),
    staleTime: 10 * 60 * 1000,
  });

  const { data: agentsData } = useQuery({
    queryKey: ['agents', projectId],
    queryFn: () => api.get<{ data: Agent[] }>(`/api/agents?projectId=${projectId}`),
    staleTime: 60 * 1000,
  });

  const items = data?.data ?? [];
  const agents = agentsData?.data ?? [];
  const workItemTypes = typesData?.data ?? [];

  const filtered = items.filter((wi) => {
    if (!search) return true;
    const q = search.toLowerCase();
    return wi.title.toLowerCase().includes(q) || String(wi.id).includes(q) || (wi.tags?.toLowerCase().includes(q) ?? false);
  });

  // Unique states for filter dropdown
  const uniqueStates = [...new Set(items.map((wi) => wi.state))].sort();
  const uniqueTypes = [...new Set(items.map((wi) => wi.type))].sort();

  return (
    <div className="flex h-full gap-6">
      {/* Main content */}
      <div className={`flex-1 min-w-0 ${selectedItem || showCreate ? 'lg:max-w-[calc(100%-25rem)]' : ''}`}>
        {/* Toolbar */}
        <div className="mb-4 flex flex-wrap items-center gap-3">
          {/* Search */}
          <div className="relative flex-1 min-w-48">
            <Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" />
            <input
              value={search}
              onChange={(e) => setSearch(e.target.value)}
              placeholder="Search by title, ID or tag…"
              className="w-full rounded-lg border border-gray-300 bg-white pl-9 pr-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-indigo-300 dark:border-gray-600 dark:bg-gray-800 dark:text-white dark:placeholder-gray-500"
            />
          </div>

          {/* Type filter */}
          <div className="flex items-center gap-2">
            <Filter size={14} className="text-gray-400" />
            <select
              value={typeFilter}
              onChange={(e) => setTypeFilter(e.target.value)}
              className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            >
              <option value="">All types</option>
              {uniqueTypes.map((t) => <option key={t} value={t}>{t}</option>)}
            </select>

            <select
              value={stateFilter}
              onChange={(e) => setStateFilter(e.target.value)}
              className="rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm dark:border-gray-600 dark:bg-gray-800 dark:text-white"
            >
              <option value="">All states</option>
              {uniqueStates.map((s) => <option key={s} value={s}>{s}</option>)}
            </select>
          </div>

          {/* Refresh */}
          <button
            onClick={() => { void refetch(); }}
            disabled={isFetching}
            className="flex items-center gap-1.5 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 disabled:opacity-50 dark:border-gray-600 dark:bg-gray-800 dark:text-gray-300 dark:hover:bg-gray-700"
          >
            <RefreshCw size={14} className={isFetching ? 'animate-spin' : ''} />
          </button>

          {/* New */}
          <button
            onClick={() => { setShowCreate(true); setSelectedItem(null); }}
            className="flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-sm font-medium text-white hover:bg-indigo-700"
          >
            <Plus size={14} /> New Work Item
          </button>
        </div>

        {/* List */}
        {isLoading ? (
          <div className="flex items-center justify-center py-20 text-gray-400">
            <Loader2 size={24} className="animate-spin" />
          </div>
        ) : error ? (
          <div className="rounded-xl border border-red-200 bg-red-50 p-6 text-center dark:border-red-800 dark:bg-red-900/20">
            <AlertCircle size={20} className="mx-auto mb-2 text-red-500" />
            <p className="text-sm text-red-600 dark:text-red-400">{getErrorMessage(error)}</p>
            <p className="mt-1 text-xs text-red-400">Make sure ADO connection is configured in Setup</p>
          </div>
        ) : filtered.length === 0 ? (
          <div className="py-16 text-center text-gray-400 dark:text-gray-600">
            {items.length === 0 ? 'No work items found. Create one to get started.' : 'No items match your filter.'}
          </div>
        ) : (
          <div className="space-y-2">
            {filtered.map((wi) => {
              const pri = priorityLabel(wi.priority);
              return (
                <button
                  key={wi.id}
                  onClick={() => { setSelectedItem(wi); setShowCreate(false); }}
                  className={`group w-full rounded-xl border p-4 text-left transition-all hover:border-indigo-300 hover:shadow-sm dark:hover:border-indigo-600
                    ${selectedItem?.id === wi.id
                      ? 'border-indigo-300 bg-indigo-50 dark:border-indigo-600 dark:bg-indigo-900/20'
                      : 'border-gray-200 bg-white dark:border-gray-700 dark:bg-gray-900'
                    }`}
                >
                  <div className="flex items-start justify-between gap-3">
                    <div className="flex items-start gap-2.5 min-w-0">
                      <span className="mt-0.5 shrink-0">{typeIcon(wi.type)}</span>
                      <div className="min-w-0">
                        <p className="truncate text-sm font-medium text-gray-900 dark:text-white">
                          {wi.title}
                        </p>
                        <div className="mt-1 flex flex-wrap items-center gap-2">
                          <span className="text-xs text-gray-400">#{wi.id}</span>
                          <span className={`rounded-full px-2 py-0.5 text-xs font-medium ${stateColor(wi.state)}`}>{wi.state}</span>
                          {pri && <span className={`text-xs ${pri.color}`}>{pri.label}</span>}
                          {wi.assignedTo && <span className="text-xs text-gray-400 dark:text-gray-600">{wi.assignedTo}</span>}
                          {wi.iterationPath && (
                            <span className="text-xs text-gray-300 dark:text-gray-700">{wi.iterationPath.split('\\').pop()}</span>
                          )}
                        </div>
                      </div>
                    </div>
                    <ChevronRight size={14} className="mt-1 shrink-0 text-gray-300 transition-transform group-hover:translate-x-0.5 group-hover:text-indigo-400 dark:text-gray-700" />
                  </div>
                </button>
              );
            })}
          </div>
        )}

        {filtered.length > 0 && (
          <p className="mt-3 text-xs text-gray-400 dark:text-gray-600">
            {filtered.length} of {items.length} item{items.length !== 1 ? 's' : ''}
            {typeFilter || stateFilter ? ' (filtered)' : ''}
          </p>
        )}
      </div>

      {/* Side panel — detail or create */}
      {(selectedItem || showCreate) && (
        <div className="w-[23rem] shrink-0 rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-700 dark:bg-gray-900 overflow-y-auto max-h-[calc(100vh-200px)]">
          {showCreate ? (
            <WorkItemForm
              projectId={projectId}
              agents={agents}
              workItemTypes={workItemTypes}
              onSuccess={() => {
                setShowCreate(false);
                qc.invalidateQueries({ queryKey: ['work-items', projectId] });
              }}
              onClose={() => setShowCreate(false)}
            />
          ) : selectedItem ? (
            <WorkItemDetail item={selectedItem} onClose={() => setSelectedItem(null)} />
          ) : null}
        </div>
      )}
    </div>
  );
}
