import { prisma } from '@nexus/db';

// ─── Types ──────────────────────────────────────────────────────────────────────

interface LogEntry {
  timestamp: string;
  level: 'info' | 'warn' | 'error';
  message: string;
  skillName?: string;
}

interface SkillResult {
  skillId: string;
  skillName: string;
  type: string;
  output: unknown;
}

// ─── Built-in Skill Handlers ────────────────────────────────────────────────────

const builtInHandlers: Record<string, (input: Record<string, unknown>) => Promise<unknown>> = {
  SummarizeBCObject: async (input) => {
    const objectName = (input.objectName as string) || 'Unknown Object';
    const objectType = (input.objectType as string) || 'Table';
    const fields = (input.fields as string[]) || [];
    const captions = (input.captions as string[]) || [];

    const fieldsList = fields.length
      ? `\n\nFields:\n${fields.map((f) => `- ${f}`).join('\n')}`
      : '';
    const captionsList = captions.length
      ? `\n\nCaptions:\n${captions.map((c) => `- ${c}`).join('\n')}`
      : '';

    return {
      summary: `## ${objectType}: ${objectName}\n\nThis is a Business Central ${objectType.toLowerCase()} object named **${objectName}**.${fieldsList}${captionsList}`,
      objectName,
      objectType,
    };
  },

  TranslateXLIFF: async (input) => {
    const sourceLanguage = (input.sourceLanguage as string) || 'en-US';
    const targetLanguage = (input.targetLanguage as string) || 'de-DE';
    const unitCount = (input.unitCount as number) || 0;
    return {
      status: 'translation_requested',
      sourceLanguage,
      targetLanguage,
      unitCount,
      message: `Translation from ${sourceLanguage} to ${targetLanguage} queued for ${unitCount} unit(s).`,
    };
  },

  ReviewTranslations: async (input) => {
    const unitCount = (input.unitCount as number) || 0;
    return {
      status: 'review_requested',
      unitCount,
      message: `Review queued for ${unitCount} translation unit(s).`,
    };
  },

  GenerateWikiPage: async (input) => {
    const title = (input.title as string) || 'Untitled';
    const content = (input.content as string) || '';
    return {
      markdown: `# ${title}\n\n${content}\n\n---\n*Generated by NexusHiveDesk Agent*`,
      title,
    };
  },

  CreateDevOpsBranch: async (input) => {
    const branchName = (input.branchName as string) || 'feature/agent-created';
    const repo = (input.repo as string) || 'unknown';
    return {
      status: 'branch_create_requested',
      branchName,
      repo,
      message: `Branch '${branchName}' creation requested on repo '${repo}'.`,
    };
  },

  CreatePullRequest: async (input) => {
    const title = (input.title as string) || 'Agent-created PR';
    const sourceBranch = (input.sourceBranch as string) || 'feature/agent-created';
    const targetBranch = (input.targetBranch as string) || 'main';
    return {
      status: 'pr_create_requested',
      title,
      sourceBranch,
      targetBranch,
      message: `Pull request '${title}' from '${sourceBranch}' to '${targetBranch}' requested.`,
    };
  },
};

// ─── Prompt Skill Executor ──────────────────────────────────────────────────────

function interpolateTemplate(template: string, variables: Record<string, unknown>): string {
  return template.replace(/\{\{(\w+)\}\}/g, (_, key: string) => {
    const val = variables[key];
    return val !== undefined ? String(val) : `{{${key}}}`;
  });
}

// ─── Main Execution Function ────────────────────────────────────────────────────

export async function executeAgentRun(
  agentId: string,
  runId: string,
  input: Record<string, unknown>,
): Promise<void> {
  const logs: LogEntry[] = [];

  function log(level: LogEntry['level'], message: string, skillName?: string) {
    logs.push({ timestamp: new Date().toISOString(), level, message, skillName });
  }

  try {
    // Mark as running
    await prisma.agentRun.update({
      where: { id: runId },
      data: { status: 'running' },
    });

    // Fetch agent with skills
    const agent = await prisma.agent.findUnique({
      where: { id: agentId },
      include: {
        skills: {
          include: { skill: true },
          orderBy: { createdAt: 'asc' },
        },
      },
    });

    if (!agent) {
      throw new Error('Agent not found');
    }

    log('info', `Starting agent run for "${agent.name}"`);

    const skills = agent.skills.map((as) => as.skill);
    if (skills.length === 0) {
      log('info', 'No skills attached — completing with no output');
      await prisma.agentRun.update({
        where: { id: runId },
        data: {
          status: 'completed',
          output: JSON.stringify({ message: 'No skills to execute' }),
          logs: JSON.stringify(logs),
          endedAt: new Date(),
        },
      });
      return;
    }

    const results: SkillResult[] = [];
    let currentInput = { ...input };

    for (const skill of skills) {
      log('info', `Executing skill: ${skill.name} (type: ${skill.type})`, skill.name);

      try {
        let output: unknown;

        if (skill.type === 'code' && skill.builtIn) {
          // Built-in skill handler
          const handler = builtInHandlers[skill.name];
          if (!handler) {
            log('warn', `No built-in handler for skill "${skill.name}" — skipping`, skill.name);
            continue;
          }
          output = await handler(currentInput);
        } else if (skill.type === 'prompt' && skill.promptTemplate) {
          // Prompt-type skill — interpolate template
          const interpolated = interpolateTemplate(skill.promptTemplate, currentInput);
          output = { prompt: interpolated, note: 'AI call placeholder — connect to AI provider for real execution' };
          log('info', `Prompt interpolated (${interpolated.length} chars)`, skill.name);
        } else {
          log('warn', `Skill "${skill.name}" has unsupported type "${skill.type}" — skipping`, skill.name);
          continue;
        }

        results.push({ skillId: skill.id, skillName: skill.name, type: skill.type, output });
        log('info', `Skill "${skill.name}" completed successfully`, skill.name);

        // Pass output as input to the next skill
        if (output && typeof output === 'object') {
          currentInput = { ...currentInput, ...(output as Record<string, unknown>), _previousSkillOutput: output };
        }
      } catch (skillError) {
        const errMsg = skillError instanceof Error ? skillError.message : String(skillError);
        log('error', `Skill "${skill.name}" failed: ${errMsg}`, skill.name);
        throw new Error(`Skill "${skill.name}" failed: ${errMsg}`);
      }
    }

    log('info', `Agent run completed — ${results.length} skill(s) executed`);

    await prisma.agentRun.update({
      where: { id: runId },
      data: {
        status: 'completed',
        output: JSON.stringify(results),
        logs: JSON.stringify(logs),
        endedAt: new Date(),
      },
    });
  } catch (error) {
    const errMsg = error instanceof Error ? error.message : String(error);
    log('error', `Agent run failed: ${errMsg}`);

    await prisma.agentRun.update({
      where: { id: runId },
      data: {
        status: 'failed',
        error: errMsg,
        logs: JSON.stringify(logs),
        endedAt: new Date(),
      },
    });
  }
}
